services:
  - type: web
    name: holoduel-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SKIP_HOSTING_GAME
        value: true
      - key: PYTHON_VERSION
        value: 3.10.0 